# This is a build file for Travis CI.
# See: https://travis-ci.org/mbitsnbites/buildcache

language: cpp

matrix:
  include:
    # Linux GCC
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
            - ninja-build
      script:
        - mkdir out && cd out
        - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ../src
        - cmake --build .
        - ctest

    # macOS clang
    - os: osx
      compiler: clang
      addons:
        homebrew:
          packages:
            - ninja
      script:
        - mkdir out && cd out
        - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ../src
        - cmake --build .
        - ctest

    # Windows MSVC 2017
    - os: windows
      compiler: msvc
      env:
        - MATRIX_EVAL="CC=cl.exe && CXX=cl.exe"
      before_install:
        - eval "${MATRIX_EVAL}"
      install:
        - choco install ninja
      script:
        - mkdir out && cd out
        - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 &&
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ../src &&
          ninja'
        - ninja test

